name: Rust CI

on: [push]

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Building
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Demo
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-make
          cargo make

      - name: Demo is building
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package demo
